id: EDL Performance Test - Timeout
version: -1
fromversion: 5.5.0
name: EDL Performance Test - Timeout
starttaskid: "0"
tasks:
  "0":
    id: "0"
    taskid: a95528a1-86e4-4266-80b8-c9d291746ae5
    type: start
    task:
      id: a95528a1-86e4-4266-80b8-c9d291746ae5
      version: -1
      name: ""
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "1"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 50
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "1":
    id: "1"
    taskid: b560ef77-ea8e-42be-8f7d-2b6d31adae5d
    type: title
    task:
      id: b560ef77-ea8e-42be-8f7d-2b6d31adae5d
      version: -1
      name: Timeout 3
      type: title
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "2"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 195
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "2":
    id: "2"
    taskid: da2a9e0b-0a96-43a7-8545-10a8f9aa6df7
    type: playbook
    task:
      id: da2a9e0b-0a96-43a7-8545-10a8f9aa6df7
      version: -1
      name: EDL Indicator Performance Test
      playbookName: EDL Indicator Performance Test
      type: playbook
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "3"
    scriptarguments:
      c:
        simple: ${inputs.c}
      "n":
        simple: ${inputs.n}
      results_map:
        simple: ${inputs.results_map}
      t:
        simple: "3"
      url:
        simple: ${inputs.url}
      z:
        simple: ${inputs.z}
    separatecontext: true
    loop:
      iscommand: false
      exitCondition: ""
      wait: 1
      max: 100
    view: |-
      {
        "position": {
          "x": 50,
          "y": 340
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "3":
    id: "3"
    taskid: 8338090a-e4df-4dfa-8ecb-7b6ab4015891
    type: title
    task:
      id: 8338090a-e4df-4dfa-8ecb-7b6ab4015891
      version: -1
      name: Timeout 5
      type: title
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "4"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 515
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "4":
    id: "4"
    taskid: 44c55874-4b79-4af0-895a-24bee7e034f1
    type: playbook
    task:
      id: 44c55874-4b79-4af0-895a-24bee7e034f1
      version: -1
      name: EDL Indicator Performance Test
      playbookName: EDL Indicator Performance Test
      type: playbook
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "5"
    scriptarguments:
      c:
        simple: ${inputs.c}
      "n":
        simple: ${inputs.n}
      results_map:
        simple: ${inputs.results_map}
      t:
        simple: "5"
      url:
        simple: ${inputs.url}
      z:
        simple: ${inputs.z}
    separatecontext: true
    loop:
      iscommand: false
      exitCondition: ""
      wait: 1
      max: 100
    view: |-
      {
        "position": {
          "x": 50,
          "y": 660
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "5":
    id: "5"
    taskid: 74b4a7c7-39d2-410c-8c8e-9c9e81fbefd2
    type: title
    task:
      id: 74b4a7c7-39d2-410c-8c8e-9c9e81fbefd2
      version: -1
      name: Timeout 10
      type: title
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "6"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 835
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "6":
    id: "6"
    taskid: f83b2076-791c-40fc-8f78-4912e9365448
    type: playbook
    task:
      id: f83b2076-791c-40fc-8f78-4912e9365448
      version: -1
      name: EDL Indicator Performance Test
      playbookName: EDL Indicator Performance Test
      type: playbook
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "7"
    scriptarguments:
      c:
        simple: ${inputs.c}
      "n":
        simple: ${inputs.n}
      results_map:
        simple: ${inputs.results_map}
      t:
        simple: "10"
      url:
        simple: ${inputs.url}
      z:
        simple: ${inputs.z}
    separatecontext: true
    loop:
      iscommand: false
      exitCondition: ""
      wait: 1
      max: 100
    view: |-
      {
        "position": {
          "x": 50,
          "y": 980
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "7":
    id: "7"
    taskid: 9c9b075f-f19f-4634-8659-543829d94bc1
    type: title
    task:
      id: 9c9b075f-f19f-4634-8659-543829d94bc1
      version: -1
      name: Timeout 30
      type: title
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "8"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 1155
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "8":
    id: "8"
    taskid: 0820b2f7-6743-43bd-8484-7ce4da4deb06
    type: playbook
    task:
      id: 0820b2f7-6743-43bd-8484-7ce4da4deb06
      version: -1
      name: EDL Indicator Performance Test
      playbookName: EDL Indicator Performance Test
      type: playbook
      iscommand: false
      brand: ""
    scriptarguments:
      c:
        simple: ${inputs.c}
      "n":
        simple: ${inputs.n}
      results_map:
        simple: ${inputs.results_map}
      t:
        simple: "30"
      url:
        simple: ${inputs.url}
      z:
        simple: ${inputs.z}
    separatecontext: true
    loop:
      iscommand: false
      exitCondition: ""
      wait: 1
      max: 100
    view: |-
      {
        "position": {
          "x": 50,
          "y": 1300
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 1345,
        "width": 380,
        "x": 50,
        "y": 50
      }
    }
  }
inputs:
- key: url
  value: {}
  required: false
  description: The URL of the EDL instance with with query in the end
  playbookInputQuery: null
- key: "n"
  value: {}
  required: false
  description: ""
  playbookInputQuery: null
- key: z
  value: {}
  required: false
  description: ""
  playbookInputQuery: null
- key: results_map
  value: {}
  required: false
  description: ""
  playbookInputQuery: null
- key: c
  value: {}
  required: false
  description: Concurrent requests to be sent.
  playbookInputQuery: null
outputs:
- contextPath: Hey
  type: unknown
sourceplaybookid: 37d1cfda-2d21-4eab-87fa-4449cf2f5427
tests:
  - No test
