id: GoogleMaps_Test
version: -1
vcShouldKeepItemLegacyProdMachine: false
name: GoogleMaps_Test
starttaskid: "0"
tasks:
  "0":
    id: "0"
    taskid: 7f104dae-d294-4a89-81da-d747b89f6485
    type: start
    task:
      id: 7f104dae-d294-4a89-81da-d747b89f6485
      version: -1
      name: ""
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "1"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 50
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "1":
    id: "1"
    taskid: a585a297-341a-4a42-8961-db6d7c23e05a
    type: regular
    task:
      id: a585a297-341a-4a42-8961-db6d7c23e05a
      version: -1
      name: DeleteContext
      script: DeleteContext
      type: regular
      iscommand: true
      brand: ""
    nexttasks:
      '#none#':
      - "2"
    scriptarguments:
      all:
        simple: "yes"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 200
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "2":
    id: "2"
    taskid: fd65bf80-cded-4d6e-8b15-389b75b2eac5
    type: regular
    task:
      id: fd65bf80-cded-4d6e-8b15-389b75b2eac5
      version: -1
      name: google-maps-geocode
      script: '|||google-maps-geocode'
      type: regular
      iscommand: true
      brand: ""
    nexttasks:
      '#none#':
      - "3"
    scriptarguments:
      search_address:
        simple: Paloalto Networks Tel Aviv
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 400
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "3":
    id: "3"
    taskid: 38d708bb-7796-455a-824e-0ca5830f7803
    type: condition
    task:
      id: 38d708bb-7796-455a-824e-0ca5830f7803
      version: -1
      name: Verify Outputs
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      "yes":
      - "4"
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: isEqualNumber
          left:
            value:
              simple: GoogleMaps.lat
            iscontext: true
          right:
            value:
              simple: "32.0688581"
      - - operator: isEqualNumber
          left:
            value:
              simple: GoogleMaps.lng
            iscontext: true
          right:
            value:
              simple: "34.7940206"
      - - operator: isEqualString
          left:
            value:
              simple: GoogleMaps.SearchAddress
            iscontext: true
          right:
            value:
              simple: Paloalto Networks Tel Aviv
      - - operator: isEqualString
          left:
            value:
              simple: GoogleMaps.Address
            iscontext: true
          right:
            value:
              simple: Yigal Alon St 94a, Tel Aviv-Yafo, 6789155, Israel
      - - operator: isEqualString
          left:
            value:
              simple: GoogleMaps.Country
            iscontext: true
          right:
            value:
              simple: Israel
    view: |-
      {
        "position": {
          "x": 50,
          "y": 600
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "4":
    id: "4"
    taskid: a7e80ba6-f24d-419d-80ca-37e059fb8f06
    type: title
    task:
      id: a7e80ba6-f24d-419d-80ca-37e059fb8f06
      version: -1
      name: Test Done
      type: title
      iscommand: false
      brand: ""
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 800
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 815,
        "width": 380,
        "x": 50,
        "y": 50
      }
    }
  }
inputs: []
outputs: []
fromversion: 5.5.0