
default:
  image: docker-io.artifactory.pan.local/devdemisto/gitlab-content-ci:1.0.0.18999
  artifacts:
    expire_in: 30 days
    paths:
      - /builds/xsoar/content/artifacts/*
    when: always

stages:
  - notify


include:
  - local: .gitlab/ci/global.yml


slack-notify:
  stage: notify
  extends: .default-job-settings
  # rules:
  #   - if: $CI_COMMIT_BRANCH == "master" || $SLACK_CHANNEL != "dmst-content-team"
  script:
    - set | grep -E "^NIGHTLY=|^INSTANCE_TESTS=|^SERVER_BRANCH_NAME=|^ARTIFACT_BUILD_NUM=|^DEMISTO_SDK_NIGHTLY=|^TIME_TO_LIVE=|^CONTRIB_BRANCH=|^FORCE_PACK_UPLOAD=|^PACKS_TO_UPLOAD=|^BUCKET_UPLOAD=|^GCS_MARKET_BUCKET=|^SLACK_CHANNEL=|^TERM=|^FORCE_COLOR=|^CI_.*?="
    - python3 ./Tests/scripts/gitlab_slack_notifier.py -p "$PIPELINE_TO_QUERY" -s "$SLACK_TOKEN" -c "$GITLAB_STATUS_TOKEN" -ca "$ARTIFACTS_FOLDER" -ch "$SLACK_CHANNEL" -tw "$WORKFLOW"
  needs:
    - pipeline: $PIPELINE_TO_QUERY
      job: $JOB_NAME
